### ISSUE TITLE
A new Plugin suggestion

### ISSUE THREAD

**Issue by misspent** [vBread/bd-contributions#13]
Plugin Name: QuickEditLastMessage

Reason/Use Cases: Instead of "QuickLastMessage" it'll make it so when you press the down key you edit your last message or perhaps add the option into "QuickLastMessage"

Thank you for your useful plugins

**Comment by olivermrose** [comment]
This is already a native Discord feature that you can access by pressing the up arrow.

**Comment by misspent** [comment]
> This is already a native Discord feature that you can access by pressing the up arrow.

And that's why this is my name... Thank you you just saved a soul
