### ISSUE TITLE
Cannot open settings

### ISSUE THREAD

**Issue by CahyaAziz** [vBread/bd-contributions#15]
## Description
I can't open settings for the BetterCodeblocks plugin. Even after deleting it and installing it back
### Reproduction Steps

Clicking on the settings icon

### Screenshots
![44](https://user-images.githubusercontent.com/64559304/126069493-20eb7d93-bd0b-4704-a4c5-66c55774f06c.PNG)

### Additional Info

- Plugin Name: BetterCodeblocks
- Discord Release: Stable (Better discord)
- Platform: PC

**Comment by Glaived** [comment]
Works for me
