### ISSUE TITLE
BetterCodeBlocks copy code button is missing (padding issue.)

### ISSUE THREAD

**Issue by ghost** [vBread/bd-contributions#23]
BetterCodeBlocks copy button is hidden because the padding is off, both with and without themes.

### Reproduction Steps
Try to hover the copy button, it's padding is off, removing the 0 before 10px makes it appear again.

### Screenshots
https://i.imgur.com/wZtWFqN.gif

- Plugin Name:BetterCodeBlocks
- Discord Release: Stable.

**Comment by Glaived** [comment]
I think it comes from the fact that the button has no text (when it should have one), it is not a padding problem.

**Comment by Mattwmaster58** [comment]
Contributing the issue I think is that `Messages.COPY` is undefined which is what `React.createElement` is trying to create the element with.
