### ISSUE TITLE
Quick messages not working

### ISSUE THREAD

**Issue by maddaxlallatin** [vBread/bd-contributions#24]
## Description
 Quick messages no longer work
### Reproduction Steps
Send text to a channel
hit down arrow
notice text box is not filled with the last message

### Additional Info
- Plugin Name: quickMessages
- Discord Release: 
-Stable

**Comment by Mattwmaster58** [comment]
I noticed this as well. 
```
3cf77b996e1fcc8c8896.js:126 Uncaught TypeError: Cannot read property 'undefined' of undefined
    at y (6fcc6d7f29594b59be3e.js:formatted:15547)
    at HTMLDocument.<anonymous> (QuickLastMessage.plugin.js:82)
    at HTMLDocument.r (3cf77b996e1fcc8c8896.js:126)
 ```
 It's calling an internal function or at least appears to, which tries to read something undefined.

**Comment by Mattwmaster58** [comment]
For anyone looking to solve this themselves while waiting, go ahead to line 72 in the file and make this change:
```diff
-const { getChannelId } = WebpackModules.getByProps('getChannelId')
+const { getChannelId } = WebpackModules.getByProps('getLastSelectedChannelId');
```

**Comment by xFGhoul** [comment]
thanks
