### ISSUE TITLE
Better Code Blocks: First indent level is hidden

### ISSUE THREAD

**Issue by PowerUser64** [vBread/bd-contributions#27]
### Reproduction Steps

Write some code that has different levels of indent, wrap it in a code block, and send the message. 

### Screenshots

Input:
![image](https://user-images.githubusercontent.com/24578572/145982509-6060b346-e2be-4c19-bda4-64db57cdeb7f.png)

Vanilla:
![image](https://user-images.githubusercontent.com/24578572/145981941-f7a25939-735e-477f-afd0-e54a0c1e482e.png)

Better code blocks:
![image](https://user-images.githubusercontent.com/24578572/145982007-6abc80b3-ef4c-4141-a20d-3d54c958e0a2.png)

### Additional Info

- Plugin Name: BetterCodeblocks
- Discord Release: Stable
- Platform: Linux

**Comment by Mattwmaster58** [comment]
duplicate: #17
PR: #21
