### ISSUE TITLE
[BetterCodeblocks] Assembly Syntax Highlighting

### ISSUE THREAD

**Issue by marcussacana** [vBread/bd-contributions#37]
## Description
Look like the discord don't has support for highlighting assembly x86 code, if possible, add that in the plugin.

- Plugin Name: BetterCodeblocks

**Comment by nathanfranke** [comment]
GDScript would also be cool. It is already supported by GitHub (Not trying to take over the issue).

**Comment by NicoBren** [comment]
> ## Description
> Look like the discord don't has support for highlighting assembly x86 code, if possible, add that in the plugin.
> 
> * Plugin Name: BetterCodeblocks

use ```x86asm

![image](https://user-images.githubusercontent.com/89282630/182882464-9d205817-9279-436c-9218-87f12e43a135.png)
![image](https://user-images.githubusercontent.com/89282630/182882305-cc07e12f-6d38-4a39-94dc-e914fdfa03d7.png)

**Comment by marcussacana** [comment]
thank you
