### ISSUE TITLE
counts twice

### ISSUE THREAD

**Issue by Ash3781** [vBread/bd-contributions#7]
the plugin counts the lines twice, once with a bit of space and once with like "snapped to the line" as it should be
![Screenshot 2021-03-25 13:10:44](https://user-images.githubusercontent.com/37660156/115145256-ec774780-a050-11eb-884f-168db9cfb10d.png)

**Comment by olivermrose** [comment]
Which version of the plugin are you using?

**Comment by Ash3781** [comment]
> Which version of the plugin are you using?

version is 1.2.0
